root = "/app"
tmp_dir = "/app/tmp/worker"

[build]
    cmd = "go build -o /app/tmp/worker/main /app/cmd/worker/"

    entrypoint = "/app/tmp/worker/main"

    include_ext = ["go", "proto", "tmpl", "html"]

    exclude_dir = ["tmp", "vendor", "test", "deployments"]

    delay = 1000

[log]
    time = true
    main_only = true

[color]
    app = "cyan"