root = "."
tmp_dir = "tmp"

[build]
    cmd = "go build -o ./tmp/controller ./cmd/controller/"

    bin = "./tmp/controller"

    include_ext = ["go", "proto", "tmpl", "html"]

    exclude_dir = ["tmp", "vendor", "test", "deployments"]

    delay = 1000

[log]
    time = true
    main_only = true