root = "/app"
tmp = "/app/tmp/cli"

[build]
    cmd = "go build -o /app/tmp/cli/main /app/cmd/cli/"

    entrypoint = "/app/tmp/cli/main"

    include_ext = ["go", "proto", "html", "tmpl"]

    exclude_dir = ["tmp", "vendor", "test", "deployments"]

    delay = 1000

[log]
    time = true
    main_only = true

[color]
    app = "cyan"