name: orchestrator

services:
  localstack:
    image: localstack/localstack:3
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      SERVICES: s3,dynamodb,lambda
      LAMBDA_RUNTIME_ENVIRONMENT_TIMEOUT: 30
      LAMBDA_INIT_USER: root
      DEBUG: 1
    volumes:
      - ./scripts/localstack-init.sh:/etc/localstack/init/ready.d/init.sh
      - lambda-bin:/app/lambda
      - /var/run/docker.sock:/var/run/docker.sock
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4566/_localstack/health"]
      interval: 5s
      timeout: 5s
      retries: 15
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "2m"
        max-file: "3"
  controller:
    image: codebuddha/orchestrator:latest
    command: /app/bin/controller
    container_name: controller
    ports:
      - "50051:50051"
    volumes:
      - lambda-bin:/app/lambda
    environment:
      AWS_ENDPOINT_URL: http://localstack:4566
      KAFKA_BROKERS: "kafka:29092"
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_REGION: us-east-1
    depends_on:
      localstack:
        condition: service_healthy
      kafka:
        condition: service_started
  worker:
    image: codebuddha/orchestrator:latest
    command: /app/bin/worker
    container_name: worker
    environment:
      AWS_ENDPOINT_URL: http://localstack:4566
      KAFKA_BROKERS: "kafka:29092"
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
      AWS_REGION: us-east-1
    depends_on:
      localstack:
        condition: service_healthy
      controller:
        condition: service_started
      kafka:
        condition: service_started

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: kafka
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

volumes:
  lambda-bin: