---
- name: Install K3s on master
  shell: curl -sfL https://get.k3s.io | sh -s - --tls-san 192.168.56.10 --node-ip 192.168.56.10 --flannel-iface=enp0s8
  when: inventory_hostname in groups['master']

- name: Retrieve K3s token from master
  command: cat /var/lib/rancher/k3s/server/node-token
  register: master_token
  when: inventory_hostname in groups['master']

- name: Install K3s on worker and join cluster
  shell: |
    curl -sfL https://get.k3s.io | \
    K3S_URL="https://192.168.56.10:6443" \
    K3S_TOKEN="{{ hostvars[groups['master'][0]]['master_token']['stdout'] }}" \
    sh -s - --node-ip 192.168.56.11 --flannel-iface=enp0s8
  when: inventory_hostname in groups['workers']

- name: Fetch the K3s config file for my host machine
  fetch:
    src: /etc/rancher/k3s/k3s.yaml
    dest: ~/.kube/config
    flat: yes
  when: inventory_hostname in groups['master']

- name: Update the K8s config IP address to master vm IP
  delegate_to: localhost
  become: no
  replace:
    path: ~/.kube/config
    regexp: '127\.0\.0\.1'
    replace: '192.168.56.10'
  when: inventory_hostname in groups['master']