---
- name: Install K3s on master
  shell: curl -sfL https://get.k3s.io | sh -s - --tls-san 192.168.56.10 --node-ip 192.168.56.10 --flannel-iface=enp0s8
  when: inventory_hostname in groups['master']

- name: Retrieve K3s token from master
  command: cat /var/lib/rancher/k3s/server/node-token
  register: master_token
  when: inventory_hostname in groups['master']

- name: Install K3s on worker and join cluster
  shell: |
    curl -sfL https://get.k3s.io | \
    K3S_URL="https://192.168.56.10:6443" \
    K3S_TOKEN="{{ hostvars[groups['master'][0]]['master_token']['stdout'] }}" \
    sh -s - --node-ip 192.168.56.11 --flannel-iface=enp0s8
  when: inventory_hostname in groups['workers']

- name: Fetch the K3s config file for my host machine
  fetch:
    src: /etc/rancher/k3s/k3s.yaml
    dest: ~/.kube/config
    flat: yes
  when: inventory_hostname in groups['master']

- name: Update the K8s config IP address to master vm IP
  delegate_to: localhost
  become: no
  replace:
    path: ~/.kube/config
    regexp: '127\.0\.0\.1'
    replace: '192.168.56.10'
  when: inventory_hostname in groups['master']

- name: Install Helm on master VM
  shell: |
    curl -fsSl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
  args:
    creates: /usr/local/bin/helm
  when: inventory_hostname in groups['master']

- name: Add Helm chart repos
  shell: |
    helm repo add bitnami https://charts.bitnami.com/bitnami
    helm repo add grafana https://grafana.github.io/helm-charts
    helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
    helm repo update
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
  when: inventory_hostname in groups['master']

- name: Deploy kafka using helm
  shell: |
    helm upgrade --install kafka bitnami/kafka \
    -f /vagrant/k8s/kafka-values.yaml
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
  when: inventory_hostname in groups['master']

- name: deploy loki stack (loki | promtail | grafana)
  shell: |
    helm upgrade --install loki grafana/loki-stack \
    --set grafana.enabled=true,promtail.enabled=true
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
  when: inventory_hostname in groups['master']

- name: deploy prometheus
  shell: |
    helm upgrade --install prometheus prometheus-community/prometheus \
      --set alertmanager.enabled=false,pushgateway.enabled=false,nodeExporter.enabled=false,server.persistentVolume.enabled=false
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
  when: inventory_hostname in groups['master']

- name: deploy orchestrator application manifests
  shell: |
    kubectl apply \
      -f /vagrant/k8s/localstack-init-config.yaml \
      -f /vagrant/k8s/localstack-service.yaml \
      -f /vagrant/k8s/localstack-deployment.yaml \
      -f /vagrant/k8s/config.yaml \
      -f /vagrant/k8s/secret.yaml \
      -f /vagrant/k8s/controller-deployment.yaml \
      -f /vagrant/k8s/controller-service.yaml \
      -f /vagrant/k8s/worker-deployment.yaml
  environment:
    KUBECONFIG: /etc/rancher/k3s/k3s.yaml
  when: inventory_hostname in groups['master']