syntax = "proto3";

import "google/protobuf/empty.proto";

package orchestrator;

option go_package = "github.com/jamwujustyle/distributed-task-orchestrator";


enum TaskStatus {
    PENDING = 0;
    RUNNING = 1;
    COMPLETED = 2;
    FAILED = 3;
}

message TaskId {
    string ID = 1;
}

message Task {
    string id = 1;
    string script_s3_key = 2;
    TaskStatus status = 3;
}
message UpdateTaskRequest {
    string id = 1;
    TaskStatus status = 2;
}

message Script {
    bytes content = 1;
}

message ScriptKey {
    string key = 1;
}

service TaskService {
    rpc SubmitTask(Task) returns (TaskId);
    rpc RetrieveTask(TaskId) returns (Task);
    rpc UpdateTask(UpdateTaskRequest) returns (google.protobuf.Empty);
    rpc PollTasks(google.protobuf.Empty) returns (stream Task);
    rpc UploadScript(Script) returns (ScriptKey);
    rpc RetrieveScript(ScriptKey) returns (Script);
    rpc ListScripts(google.protobuf.Empty) returns (stream ScriptKey);
}

